- name: ping the server
  hosts: web
  tasks: #list of tasks/modules/collections
  - name: pinging the server
    ansible.builtin.ping:

- hosts: web
  tasks:
    - name: Installing httpd
      yum: name=httpd state=present
      