- name: variables
  hosts: localhost
  vars:
    course: "ansible"
    trainer: "prasad"
    duration: "120 hrs"
  tasks:
  - name: printing the information
    ansible.builtin.debug:
     msg: "Hi , we are learning {{ course }}, from {{ trainer }}, duraion is {{ duration }}." 


