- name: variables from prompt
  hosts: localhost
  become: yes
  vars:
  - name: USERNAME
    prompt: Please enter username
  - name: PASSWORD
    prompt: please enter password
    private: yes  

  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "hi, please enter username: {{USERNAME}}, enter password: {{PASSWORD}}."