- name: variables from prompt
  hosts: localhost
  become: yes
  vars_prompt:
  - name: USERNAME
    prompt: Please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true 

  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "hi, please enter username: {{USERNAME}}. enter password: {{PASSWORD}}"
