- name: variables from prompt
  hosts: localhost
  become: yes
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "hi, please enter username: {{USERNAME}}. enter password: {{PASSWORD}}"
