- name: variables form inventory
  hosts: localhost
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "hi,we are learning {{Course}},from {{Trainer}},duraion is {{Duraion}}."
