- name: variables form inventory
  hosts: localhost
  become: yes
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "hi we are learning {{course}} from {{trainer}} duraion is {{duraion}}"
